### ISSUE TITLE
Meeting Title

### ISSUE THREAD

**Issue by ingo916** [MMM-CalendarExt2/MMM-CalendarExt2#269] opened 2023-02-05 04:20 UTC
I am having this issue again somehow, I fixed this before and cannot remember what I did to make it show the calendar event title rather than the name of the organizer.
My calendar events are displaying the name of the organizer and not the title of the meeting. Where would I configure this change?

![image](https://user-images.githubusercontent.com/41309095/216797960-aef73ad5-6aa8-4712-933d-2552ef21b755.png)

		{
			"module": "MMM-CalendarExt2",
			"config": {
				"calendars": [
				{
					"name": "WCM",
					"url": "https://outlook.office365.com/owa/calendar/............./calendar.ics",
						"auth": {
							"method": "basic",
							"user": "user id",
							"pass": "password",
							
						}

				},
			],
				"views": [
				{
					"mode": "week",
					"position": "bottom_bar",
					"slotCount": "mode:weekly", "fromNow":0, "slotCount":2				
				},
			],
				"scenes": [
				{
					
					"name": "DEFAULT",
				},
			],
			},
				
		},

**Comment by klaernie** [comment] 2023-02-05 14:02
Duplicate of #122

**Closed by klaernie** 2023-02-05 14:02 UTC

**Comment by ingo916** [comment] 2023-02-08 20:16
Fixed, Exchange online issue
https://medium.com/meeting-room-365/issue-display-shows-organizers-name-instead-of-subject-731f4cf414ac

A Resource mailbox is configured to AutoAccept in an Microsoft Exchange Server or Office 365 environment.
You send a meeting request to the Resource mailbox.
The meeting request is accepted automatically, and the meeting subject is displayed correctly in the organizer’s mailbox.

**Why is this happening?**
This is default behavior for Exchange Web Services and Office 365. It occurs because two configuration parameters, AddOrganizerToSubject and DeleteSubject are set to $True.

**Solution**
For Office 365, Exchange Server 2016, Exchange Server 2013 or Exchange Server 2010 (PowerShell):

Set-CalendarProcessing -Identity <RESOURCEMAILBOX> -DeleteSubject $False -AddOrganizerToSubject $False
